[package]
name = "sappho-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amq-bot = { path = "../amq-bot" }
log = "0.4.18"
thiserror = "1.0.40"
serde_json = "1.0.96"
