# fly.toml app configuration file generated for snowy-hill-5293 on 2023-05-28T19:00:44+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snowy-hill-5293"
primary_region = "syd"


[env]
  RUST_LOG = "info"

# [mounts]
#   source="amq_data"
#   destination="/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
