# ignore everything from build context (parent)
*

# allow directories
!/acg-bot
!/chokotan-bot
!/stream-song
!/song-artist
!/database
!/amq-types

# disallow
*/target
*/*.bat
*/.idea
*/.vscode
